re = int ( input ( "Entrez la partie réelle du nombre complexe : " ))
im = int ( input ( "Entrez la partie imaginaire du nombre complexe : "))
z = complex (re,im)
print ("Le nombre complexe est ", z)
print ("Son module est ", abs(z))
print ("Son conjugué est ", z.conjugate ())
print ("Son carré est ", z**2)